[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.geojson"
  [headers.values]
    Content-Type = "application/geo+json"
